version: '3'
services:
  phanmai:
    #image: makara_nextjs:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3248:3000
    networks:
      - devops
networks:
  devops:
    external: true
